<?php

namespace Database\Seeders;

use App\Models\RhythmSymbol;
use Illuminate\Database\Seeder;

class RhythmSymbolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $elements = [
            [1, [["type" => "bar"]], 0,0],
            [2, [["type" => "n", "value" => 4]], 1,0],
            [3, [["type" => "r", "value" => 4]], 1,0],
            [4, [["type" => "n", "value" => 2]], 2,0],
            [5, [["dot" => true, "type" => "n", "value" => 2]], 3,0],
            [6, [["type" => "r", "value" => 2]], 2,0],
            [7, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 1,0],
            [8, [["type" => "n", "value" => 8], ["type" => "r", "value" => 8]], 1,0],
            [9, [["type" => "r", "value" => 8], ["type" => "n", "value" => 8]], 1,0],
            [10, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 2,0],
            [11, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 2,0],
            [12, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 4,0],
            [13, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1,0],
            [14, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1,0],
            [15, [["type" => "n", "value" => 4], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 4]], 2,1],
            [16, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 2,1],
            [17, [["type" => "n", "value" => 2], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 4]], 3,2],
            [18, [["type" => "n", "value" => 4], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 2]], 3,1],
            [19, [["dot" => true, "type" => "n", "value" => 4]], 1.5,NULL],
            [20, [["dot" => true, "type" => "r", "value" => 4]], 1.5,NULL],
            [21, [["dot" => true, "type" => "n", "value" => 4], ["type" => "bar"], ["dot" => true, "tie" => true, "type" => "n", "value" => 4]], 3,1.5],
            [22, [["dot" => true, "type" => "n", "value" => 4], ["type" => "bar"], ["dot" => true, "tie" => true, "type" => "n", "value" => 2]], 4.5,1.5],
            [23, [["dot" => true, "type" => "n", "value" => 2], ["type" => "bar"], ["dot" => true, "tie" => true, "type" => "n", "value" => 4]], 4.5,3],
            [24, [["dot" => true, "type" => "r", "value" => 2]], 3,NULL],
            [25, [["dot" => true, "type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 2,NULL],
            [26, [["type" => "n", "value" => 8], ["dot" => true, "type" => "n", "value" => 4]], 2,NULL],
            [27, [["dot" => true, "type" => "r", "value" => 4], ["type" => "n", "value" => 8]], 2,NULL],
            [28, [["type" => "n", "value" => 8], ["dot" => true, "type" => "r", "value" => 4]], 2,NULL],
            [29, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 3,NULL],
            [30, [["type" => "n", "value" => 2], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 3,2],
            [31, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 2]], 3,1],
            [32, [["dot" => true, "type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 4]], 3,2],
            [33, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 3,1],
            [34, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 1.5,NULL],
            [35, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 1.5,NULL],
            [36, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4]], 1.5,NULL],
            [37, [["type" => "r", "value" => 4], ["type" => "n", "value" => 8]], 1.5,NULL],
            [38, [["type" => "n", "value" => 8], ["type" => "r", "value" => 4]], 1.5,NULL],
            [39, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 3,NULL],
            [40, [["dot" => true, "type" => "n", "value" => 2], ["type" => "bar"], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 4.5,3],
            [41, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 3,1.5],
            [42, [["dot" => true, "type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 4]], 3,NULL],
            [43, [["dot" => true, "type" => "r", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 4]], 3,NULL],
            [44, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1,NULL],
            [45, [["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [46, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1,NULL],
            [47, [["dot" => true, "type" => "r", "value" => 8], ["type" => "n", "value" => 16]], 1,NULL],
            [48, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1,NULL],
            [49, [["type" => "n", "value" => 4], ["dot" => true, "tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 2,NULL],
            [50, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [51, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 2,NULL],
            [52, [["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [53, [["dot" => true, "type" => "r", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [54, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [55, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,1],
            [56, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,NULL],
            [57, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 4]], 1.5,NULL],
            [58, [["type" => "n", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [59, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [60, [["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 1.5,NULL],
            [61, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [62, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [63, [["dot" => true, "type" => "n", "value" => 4], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 3,1.5],
            [64, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,NULL],
            [65, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["type" => "bar"], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,1.5],
            [66, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [67, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "r", "value" => 8]], 1.5,NULL],
            [68, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1,NULL],
            [69, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1,NULL],
            [70, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1,NULL],
            [71, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8]], 1,NULL],
            [72, [["type" => "n", "value" => 16], ["dot" => true, "type" => "n", "value" => 8]], 1,NULL],
            [73, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 4], ["type" => "n", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [74, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 2,NULL],
            [75, [["type" => "r", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8]], 3,NULL],
            [76, [["type" => "r", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 1.5,NULL],
            [77, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [78, [["type" => "r", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [79, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "r", "value" => 8]], 1.5,NULL],
            [80, [["type" => "n", "value" => 4], ["type" => "r", "value" => 8]], 1.5,NULL],
            [81, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [82, [["type" => "r", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [83, [["dot" => true, "type" => "n", "value" => 4], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [84, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [85, [["type" => "n", "value" => 2], ["dot" => true, "tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,NULL],
            [86, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [87, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [88, [["type" => "r", "value" => 16], ["dot" => true, "type" => "n", "value" => 8]], 1,NULL],
            [89, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [90, [["dot" => true, "type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [91, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 4]], 3,NULL],
            [92, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 1.5,NULL],
            [93, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4]], 1.5,NULL],
            [94, [["dot" => true, "type" => "n", "value" => 2], ["tie" => true, "type" => "n", "value" => 8], ["type" => "r", "value" => 4]], 4.5,NULL],
            [95, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [96, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [97, [["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 3,NULL],
            [98, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,NULL],
            [99, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1.5,NULL],
            [100, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [101, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1.5,NULL],
            [102, [["dot" => true, "type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,NULL],
            [103, [["type" => "n", "value" => 2], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [104, [["type" => "r", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [105, [["dot" => true, "type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [106, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [107, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [108, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,NULL],
            [109, [["type" => "r", "value" => 16], ["dot" => true, "type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 2,NULL],
            [110, [["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,NULL],
            [111, [["type" => "r", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,NULL],
            [112, [["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 2,NULL],
            [113, [["type" => "r", "value" => 4, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,NULL],
            [114, [["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 4, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,NULL],
            [115, [["type" => "n", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [116, [["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "r", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,NULL],
            [117, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [118, [["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 4, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 2,NULL],
            [119, [["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 2, "in_space_of" => 3]]], 1.5,NULL],
            [120, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [121, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 4]], 1.5,NULL],
            [122, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,NULL],
            [123, [["type" => "r", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,NULL],
            [124, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 3,NULL],
            [125, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 4]], 1.5,NULL],
            [126, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8]], 1.5,NULL],
            [127, [["dot" => true, "type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,NULL],
            [128, [["type" => "r", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,NULL],
            [129, [["dot" => true, "type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 3,NULL],
            [130, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1.5,NULL],
            [131, [["dot" => true, "type" => "r", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 3,0],
            [132, [["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,0],
            [133, [["type" => "n", "value" => 8, "in_tuplet" => true], ["type" => "n", "value" => 8, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 2, "in_space_of" => 3]], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,0],
            [134, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 4]], 2,0],
            [135, [["type" => "r", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1,0],
            [136, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 2,0],
            [137, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,0],
            [138, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,0],
            [139, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1,0],
            [140, [["dot" => true, "type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 2,0],
            [141, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 2,0],
            [142, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 2,0],
            [143, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8]], 1,0],
            [144, [["type" => "r", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,0],
            [145, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,0],
            [146, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 6, "in_space_of" => 4]]], 1,0],
            [147, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,0],
            [148, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8]], 1.5,0],
            [149, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,0],
            [150, [["dot" => true, "type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 4]], 3,0],
            [151, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 4]], 3,0],
            [152, [["type" => "r", "value" => 8], ["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 3,0],
            [153, [["type" => "r", "value" => 4], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 4]], 3,0],
            [154, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16]], 3,0],
            [155, [["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,0],
            [156, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["dot" => true, "tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 2,0],
            [157, [["type" => "n", "value" => 4], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,0],
            [158, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16]], 1.5,0],
            [159, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 3,0],
            [160, [["type" => "r", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,0],
            [161, [["type" => "n", "value" => 8], ["type" => "r", "value" => 8], ["type" => "r", "value" => 8]], 1.5,0],
            [162, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8]], 1.5,0],
            [163, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,0],
            [164, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "r", "value" => 8]], 4.5,0],
            [165, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 3,0],
            [166, [["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["dot" => true, "tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1.5,0],
            [167, [["type" => "r", "value" => 8], ["type" => "n", "value" => 8], ["type" => "r", "value" => 8]], 1.5,0],
            [168, [["type" => "r", "value" => 4], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16]], 1.5,0],
            [169, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,0],
            [170, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,0],
            [171, [["type" => "r", "value" => 8], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8]], 2,0],
            [172, [["dot" => true, "type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 2,0],
            [173, [["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 2,0],
            [174, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8]], 1,0],
            [175, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1,0],
            [176, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,0],
            [177, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,0],
            [178, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8]], 2,0],
            [179, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 2,0],
            [180, [["type" => "r", "value" => 8], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 6, "in_space_of" => 4]]], 2,0],
            [181, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]]], 1.5,0],
            [182, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 4, "in_space_of" => 6]]], 1.5,0],
            [183, [["dot" => true, "type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,0],
            [184, [["type" => "n", "value" => 8], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8]], 1.5,0],
            [185, [["type" => "r", "value" => 8], ["type" => "r", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16]], 1.5,0],
            [186, [["type" => "r", "value" => 8], ["type" => "n", "value" => 16], ["type" => "n", "value" => 8], ["type" => "n", "value" => 16]], 1.5,0],
            [187, [["type" => "r", "value" => 4], ["type" => "r", "value" => 8]], 1.5,0],
            [188, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8], ["type" => "n", "value" => 8]], 1.5,0],
            [189, [["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8]], 1.5,0],
            [190, [["type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "r", "value" => 8], ["type" => "r", "value" => 8]], 1.5,0],
            [191, [["type" => "r", "value" => 4], ["type" => "n", "value" => 8], ["tie" => true, "type" => "n", "value" => 16], ["type" => "n", "value" => 16], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true], ["type" => "n", "value" => 16, "in_tuplet" => true, "tuplet_end" => true, "tuplet_type" => ["num_notes" => 3, "in_space_of" => 2]], ["type" => "n", "value" => 8]], 3,0],
            [192, [["dot" => true, "type" => "n", "value" => 8], ["type" => "n", "value" => 16], ["tie" => true, "type" => "n", "value" => 8]], 1.5,0],
        ];

        foreach ($elements as $element) {
            if (RhythmSymbol::query()->find($element[0]) == null)
                RhythmSymbol::query()->firstOrCreate([
                    'id' => $element[0],
                    'value' => $element[1],
                    'length' => $element[2],
                    'cross_bar' => $element[3],
                ]);
        }
    }
}
